kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: azurerator
subjects:
- kind: ServiceAccount
  name: azurerator
  namespace: operators
roleRef:
  kind: ClusterRole
  name: azurerator
  apiGroup: rbac.authorization.k8s.io