apiVersion: apps/v1
kind: Deployment
metadata:
  name: azurerator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: azurerator
      app.kubernetes.io/instance: flais-azurerator
  template:
    metadata:
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      labels:
        app.kubernetes.io/name: azurerator
        app.kubernetes.io/instance: flais-azurerator
    spec:
      serviceAccountName: azurerator
      securityContext:
        {}
      containers:
        - name: azurerator
          securityContext:
            {}
          image: "ghcr.io/fintlabs/azurerator:sha-0000000"
          imagePullPolicy: IfNotPresent
          env:
            - name: logging.level.no.fintlabs
              value: DEBUG
          envFrom:
            - secretRef:
                name: azurerator
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /actuator/health
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            limits:
              memory: 512Mi
              cpu: 500m
            requests:
              memory: 256Mi
              cpu: 250m